version: 1.0.3
docker_context: .
build_docker_file: docker/Dockerfile.building
build_method: pytest_run
update_method: python_update
python_version_file: pystatsd/version.py
deploy_method: python_upload_to_index
type: library
